# ArgoCD Application manifest for deploying the Helm chart
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/manirasu28/N01743131_CCGC5504_FINAL_EXAM.git'
    targetRevision: main
    path: helm/nginx-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
